dependencies {
    implementation project(':model')
    implementation 'org.springframework:spring-context'
    implementation 'org.springframework.boot:spring-boot-starter-data-r2dbc'
    implementation 'org.postgresql:r2dbc-postgresql'
    implementation 'org.reactivecommons.utils:object-mapper-api:0.1.0'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    testImplementation 'org.reactivecommons.utils:object-mapper:0.1.0'

    implementation 'org.mapstruct:mapstruct:1.5.5.Final'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'

    testImplementation('org.springframework.boot:spring-boot-starter-test') {
        // excluir versiones transitivas que podrían generar conflicto
        exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
    }
    testImplementation 'org.mockito:mockito-junit-jupiter:5.5.0'


}
test {
    useJUnitPlatform()
}