apply plugin: 'org.springframework.boot'

dependencies {
    implementation project(':jwt')
    implementation project(':message-translator')
    implementation project(':reactive-web')
    implementation project(':r2dbc-postgresql')
    implementation project(':model')
    implementation project(':usecase')

    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // Security extra (para que compile SecurityConfig)
    implementation 'org.springframework.security:spring-security-web'
    implementation 'org.springframework.security:spring-security-config'

    // JWT
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'

    implementation 'org.reactivecommons.utils:object-mapper:0.1.0'

    runtimeOnly 'org.springframework.boot:spring-boot-devtools'

    testImplementation 'com.tngtech.archunit:archunit:1.4.1'
    testImplementation 'com.fasterxml.jackson.core:jackson-databind'
    testImplementation('org.springframework.boot:spring-boot-starter-test') {
        // excluir versiones transitivas que podrían generar conflicto
        exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
    }
}

test {
    useJUnitPlatform()
}

tasks.register('explodedJar', Copy) {
    with jar
    into layout.buildDirectory.dir("exploded")
}

jar {
    enabled = false
}

bootJar {
    archiveFileName = "${project.getParent().getName()}.${archiveExtension.get()}"
}
